version: "1.0"
services:
  db:
    image: mysql:8.0.40
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD-1234}
      MYSQL_DATABASE: ${MYSQL_DATABASE-carely}
    ports:
      - '3306'
    healthcheck:
      test: [ "CMD", "mysqladmin","ping", "-h", "localhost","-u","root","-p${MYSQL_ROOT_PASSWORD-1234}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
  carely_ai:
    container_name: carely_ai
    image: whrjsgml0000/carely_ai:1
    restart: always
    ports:
      - '8000:8000'