version: "0.0.1"
services:
  app:
    container_name: carely_be
    image: carely_be
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_started
    ports:
      - "${BE_PORT-8080}:8081"
    networks:
      - test
  db:
    image: mysql:8.0.40
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD-1234}
      MYSQL_DATABASE: ${MYSQL_DATABASE-carely}
    expose:
      - "3306"
    networks:
      - test
networks:
  test:
    driver: bridge