spring:
  config:
    activate:
      on-profile: prod
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME:carely}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        show-sql: false
        default_batch_fetch_size: 100
        format_sql: false
springdoc:
  swagger-ui:
    enabled: false
jwt:
  secret: ${JWT_SECRET}
api:
  carely_ai: ${CARELY_AI_URL}
