spring:
  config:
    activate:
      on-profile: prod
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/carely
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show-sql: false
        default_batch_fetch_size: 100
        format_sql: false
    show-sql: false
jwt:
  secret: ${JWT_SECRET}
api:
  carely_ai: ${CARELY_AI_URL}
