server:
  port: 8081
spring:
  application:
    name: carely
    version: 0.0.1
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    url: ${DB_URL_CARELY}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        show-sql: true
        default_batch_fetch_size: 100
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create
  config:
    import:
      file:.env[.properties]

jwt:
  secret: abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz
