server:
  port: 8081
spring:
  application:
    name: carely
    version: 0.0.1
  config:
    import:
      - 'classpath:/ymls/application-dev.yml'
      - 'classpath:/ymls/application-prod.yml'
  profiles:
    active:
      - prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver