spring:
  application:
    name: carely
    version: 0.0.1
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    url: ${DB_URL_CARELY}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  config:
    import:
      file:.env[.properties]
