apiVersion: v1
kind: ConfigMap
metadata:
  name: config-be
data:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_JPA_HIBERNATE_DDL-AUTO: validate
  CARELY_AI_URL: svc-carely-ai.carely-ai.svc.cluster.local
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-be
type: Opaque
stringData:
  DB_HOST: ""
  DB_PORT: ""
  DB_NAME: ""
  DB_USERNAME: ""
  DB_PASSWORD: ""
  JWT_SECRET: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: be
spec:
  replicas: 3
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
        - name: be
          image: whrjsgml0000/carely_be:1.0.3
          resources:
            limits:
              memory: "2Gi"
              cpu: "1.0"
            requests:
              memory: "1Gi"
              cpu: "0.5"
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: config-be
            - secretRef:
                name: secret-be
---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: be
  ports:
    - port: 80
      targetPort: 8081
  type: ClusterIP
