apiVersion: v1
kind: Namespace
metadata:
  name: be
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-be
  namespace: be
data:
  SPRING_PROFILES_ACTIVE: prod
  DB_HOST: "10.52.64.3"
  DB_PORT: "3306"
  DB_NAME: "carely"
  DB_USERNAME: "ggho4515"
  DB_PASSWORD: "1234"
  JWT_SECRET: "qwpeoqtpuaxnvxzknaslfjpouqpotiqopkresdlmvzqworpasflzpbklkbodfa"
  CARELY_AI_URL: svc-carely-ai.carely-ai.svc.cluster.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: be
  namespace: be
spec:
  replicas: 3
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
        - name: be
          image: whrjsgml0000/carely_be:1.0.3
          # resources:
          #   limits:
          #     memory: "2Gi"
          #     cpu: "1.0"
          #   requests:
          #     memory: "1Gi"
          #     cpu: "0.5"
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: config-be
---
apiVersion: v1
kind: Service
metadata:
  name: svc-be
  namespace: be
spec:
  selector:
    app: be
  ports:
    - port: 80
      targetPort: 8081
  type: LoadBalancer
