apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  labels:
    name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - carely.life
      secretName: secret-tls
  ingressClassName: nginx
  rules:
    - host: carely.life
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: service
                port:
                  number: 80
